config/routes.rb
Dar::Application.routes.draw do
  resources :barangay_postharvest_structure_and_facility_projects

  get   "reporter_barangays", controller: "reporter_barangays", action:"index"
  post  "reporter_barangays", controller: "reporter_barangays", action:"show"

  get "data_entry", controller: "data_entry", action:"index"

  get "about",    controller: "welcome", action:"about"
  get "contacts", controller: "welcome", action:"contacts"

  resources :users

  resources :barangay_postharvest_equipment_and_machinery_projects

  resources :postharvest_structure_and_facility_typologies

  resources :postharvest_equipment_and_machinery_typologies

  resources :barangay_irrigation_project_completions

  resources :barangay_irrigation_projects

  resources :irrigation_project_typologies

  resources :barangay_bridge_project_completions

  resources :barangay_fmr_project_completions

  resources :barangay_organization_memberships

  resources :barangay_organizations

  resources :womens_organization_typologies

  resources :womens_desk_service_typologies

  resources :environmental_concern_typologies

  resources :natural_resource_typologies

  resources :farm_practice_typologies

  resources :ecosystem_typologies

  resources :other_service_typologies

  resources :recreation_service_typologies

  resources :health_service_typologies

  resources :education_service_provided_typologies

  resources :power_supply_typologies

  resources :water_system_typologies

  resources :employment_statuses

  resources :districts

  resources :marketing_area_outlet_typologies

  resources :managed_by_typologies

  resources :agri_based_enterprise_typologies

  resources :marketing_outlet_typologies

  resources :microfinance_service_provider_typologies

  resources :loan_status_typologies

  resources :credit_provider_typologies

  resources :loan_access_typologies

  resources :bridge_project_typologies

  resources :fmr_project_typologies

  resources :registering_agencies

  resources :organization_typologies

  resources :barangay_bridge_projects

  resources :barangay_fmr_projects

  resources :barangay_trainings

  resources :faps_coverages

  resources :arc_types

  resources :barangay_lti_statuses

  resources :arc_barangays

  resources :arcs

  resources :barangay_populations

  resources :barangay_politicals

  resources :barangay_geographicals

  resources :barangays

  resources :municipalities

  resources :provinces

  resources :regions

  root 'welcome#index'

  

end

app/models/arc.rb
class Arc < ActiveRecord::Base
  has_one :arc_barangay
  has_many :barangays, :through => :arc_barangays

end

app/models/arc_barangay.rb
class ArcBarangay < ActiveRecord::Base
  belongs_to :arc
  belongs_to :barangay
end

app/models/arc_type.rb
class ArcType < ActiveRecord::Base
end

app/models/barangay.rb
class Barangay < ActiveRecord::Base
  belongs_to :municipality
  has_one :arc_barangay
  has_one :arc, :through => :arc_barangay
  has_one :district, :through => :municipality
  has_one :province, :through => :district
  has_many :barangay_geographicals
  has_many :barangay_politicals
  has_many :barangay_populations
  has_many :barangay_lti_statuses
  has_many :barangay_trainings
  has_many :barangay_fmr_projects
  has_many :barangay_bridge_projects
  has_many :barangay_organizations
  has_many :barangay_organization_memberships, :through => :barangay_organizations
  has_many :barangay_irrigation_projects
  has_many :barangay_postharvest_equipment_and_machinery_projects
  has_many :barangay_postharvest_structure_and_facility_projects


  def self.search(query_ids)
    find query_ids     
  end


  def long_name
    [ 
      name ,
      (arc ? arc.name : "non-ARC") ,
      municipality.name ,
      district.name ,
      province.name ,
    ].join(", ")
  end

end

app/models/barangay_training.rb
class BarangayTraining < ActiveRecord::Base
  belongs_to :barangay
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :province
  has_many :municipalities
end

app/models/employment_status.rb
class EmploymentStatus < ActiveRecord::Base
end

app/models/faps_coverage.rb
class FapsCoverage < ActiveRecord::Base
end

app/models/municipality.rb
class Municipality < ActiveRecord::Base
  belongs_to :district
  has_many :barangays

end

app/models/province.rb
class Province < ActiveRecord::Base
  belongs_to :region
  has_many :districts
end

app/models/recreation_service_typology.rb
class RecreationServiceTypology < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :provinces

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # validates :password, length: { minimum: 8 }
  has_secure_password
  before_save { self.email = email.downcase }

  validate :password_format
  private
  def password_format
    # pw = self.password
    unless has_one_letter = password =~ /[a-zA-Z]/
      errors.add(:password, "must have at least one letter. you entered: #{password}")
      return false
    end
    unless contain_special_characters = password =~ /[\~\`\!\@\#\$\%\*\(\)\_\-\+\=\|\ ]/
      errors.add(:password, "must have at least one special character. you entered: #{password}")
      return false
    end

    unless at_least_8_chars_length = (password.length >= 8)
      errors.add(:password, "must be at least 8 characters in length. you entered: #{password}")
      return false
    end

    true    
  end
end

app/controllers/recreation_service_typologies_controller.rb
class RecreationServiceTypologiesController < ApplicationController
  before_action :set_recreation_service_typology, only: [:show, :edit, :update, :destroy]

  # GET /recreation_service_typologies
  # GET /recreation_service_typologies.json
  def index
    @recreation_service_typologies = RecreationServiceTypology.all
  end

  # GET /recreation_service_typologies/1
  # GET /recreation_service_typologies/1.json
  def show
  end

  # GET /recreation_service_typologies/new
  def new
    @recreation_service_typology = RecreationServiceTypology.new
  end

  # GET /recreation_service_typologies/1/edit
  def edit
  end

  # POST /recreation_service_typologies
  # POST /recreation_service_typologies.json
  def create
    @recreation_service_typology = RecreationServiceTypology.new(recreation_service_typology_params)

    respond_to do |format|
      if @recreation_service_typology.save
        format.html { redirect_to @recreation_service_typology, notice: 'Recreation service typology was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recreation_service_typology }
      else
        format.html { render action: 'new' }
        format.json { render json: @recreation_service_typology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recreation_service_typologies/1
  # PATCH/PUT /recreation_service_typologies/1.json
  def update
    respond_to do |format|
      if @recreation_service_typology.update(recreation_service_typology_params)
        format.html { redirect_to @recreation_service_typology, notice: 'Recreation service typology was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recreation_service_typology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recreation_service_typologies/1
  # DELETE /recreation_service_typologies/1.json
  def destroy
    @recreation_service_typology.destroy
    respond_to do |format|
      format.html { redirect_to recreation_service_typologies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recreation_service_typology
      @recreation_service_typology = RecreationServiceTypology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recreation_service_typology_params
      params.require(:recreation_service_typology).permit(:name, :description)
    end
end

app/helpers/arc_types_helper.rb
module ArcTypesHelper
end

app/helpers/arcs_helper.rb
module ArcsHelper
end

app/helpers/barangays_helper.rb
module BarangaysHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/recreation_service_typologies_helper.rb
module RecreationServiceTypologiesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reporter_helper.rb
module ReporterHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recreation_service_typologies/_form.html.erb
<%= form_for(@recreation_service_typology) do |f| %>
  <% if @recreation_service_typology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recreation_service_typology.errors.count, "error") %> prohibited this recreation_service_typology from being saved:</h2>

      <ul>
      <% @recreation_service_typology.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recreation_service_typologies/edit.html.erb
<h1>Editing recreation_service_typology</h1>

<%= render 'form' %>

<%= link_to 'Show', @recreation_service_typology %> |
<%= link_to 'Back', recreation_service_typologies_path %>

app/views/recreation_service_typologies/index.html.erb
<h1>Listing recreation_service_typologies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recreation_service_typologies.each do |recreation_service_typology| %>
      <tr>
        <td><%= recreation_service_typology.name %></td>
        <td><%= recreation_service_typology.description %></td>
        <td><%= link_to 'Show', recreation_service_typology %></td>
        <td><%= link_to 'Edit', edit_recreation_service_typology_path(recreation_service_typology) %></td>
        <td><%= link_to 'Destroy', recreation_service_typology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recreation service typology', new_recreation_service_typology_path %>

app/views/recreation_service_typologies/new.html.erb
<h1>New recreation_service_typology</h1>

<%= render 'form' %>

<%= link_to 'Back', recreation_service_typologies_path %>

app/views/recreation_service_typologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recreation_service_typology.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recreation_service_typology.description %>
</p>

<%= link_to 'Edit', edit_recreation_service_typology_path(@recreation_service_typology) %> |
<%= link_to 'Back', recreation_service_typologies_path %>