config/routes.rb
Dar::Application.routes.draw do
  resources :barangay_postharvest_structure_and_facility_projects

  get   "reporter_barangays", controller: "reporter_barangays", action:"index"
  post  "reporter_barangays", controller: "reporter_barangays", action:"show"

  get "data_entry", controller: "data_entry", action:"index"

  get "about",    controller: "welcome", action:"about"
  get "contacts", controller: "welcome", action:"contacts"

  resources :users

  resources :barangay_postharvest_equipment_and_machinery_projects

  resources :postharvest_structure_and_facility_typologies

  resources :postharvest_equipment_and_machinery_typologies

  resources :barangay_irrigation_project_completions

  resources :barangay_irrigation_projects

  resources :irrigation_project_typologies

  resources :barangay_bridge_project_completions

  resources :barangay_fmr_project_completions

  resources :barangay_organization_memberships

  resources :barangay_organizations

  resources :womens_organization_typologies

  resources :womens_desk_service_typologies

  resources :environmental_concern_typologies

  resources :natural_resource_typologies

  resources :farm_practice_typologies

  resources :ecosystem_typologies

  resources :other_service_typologies

  resources :recreation_service_typologies

  resources :health_service_typologies

  resources :education_service_provided_typologies

  resources :power_supply_typologies

  resources :water_system_typologies

  resources :employment_statuses

  resources :districts

  resources :marketing_area_outlet_typologies

  resources :managed_by_typologies

  resources :agri_based_enterprise_typologies

  resources :marketing_outlet_typologies

  resources :microfinance_service_provider_typologies

  resources :loan_status_typologies

  resources :credit_provider_typologies

  resources :loan_access_typologies

  resources :bridge_project_typologies

  resources :fmr_project_typologies

  resources :registering_agencies

  resources :organization_typologies

  resources :barangay_bridge_projects

  resources :barangay_fmr_projects

  resources :barangay_trainings

  resources :faps_coverages

  resources :arc_types

  resources :barangay_lti_statuses

  resources :arc_barangays

  resources :arcs

  resources :barangay_populations

  resources :barangay_politicals

  resources :barangay_geographicals

  resources :barangays

  resources :municipalities

  resources :provinces

  resources :regions

  root 'welcome#index'

  

end

app/models/barangay_fmr_project_completion.rb
class BarangayFmrProjectCompletion < ActiveRecord::Base
  belongs_to :barangay_fmr_project
end

app/controllers/barangay_fmr_project_completions_controller.rb
class BarangayFmrProjectCompletionsController < ApplicationController
  before_action :set_barangay_fmr_project_completion, only: [:show, :edit, :update, :destroy]

  # GET /barangay_fmr_project_completions
  # GET /barangay_fmr_project_completions.json
  def index
    @barangay_fmr_project_completions = BarangayFmrProjectCompletion.all
  end

  # GET /barangay_fmr_project_completions/1
  # GET /barangay_fmr_project_completions/1.json
  def show
  end

  # GET /barangay_fmr_project_completions/new
  def new
    @barangay_fmr_project_completion = BarangayFmrProjectCompletion.new
  end

  # GET /barangay_fmr_project_completions/1/edit
  def edit
  end

  # POST /barangay_fmr_project_completions
  # POST /barangay_fmr_project_completions.json
  def create
    @barangay_fmr_project_completion = BarangayFmrProjectCompletion.new(barangay_fmr_project_completion_params)

    respond_to do |format|
      if @barangay_fmr_project_completion.save
        format.html { redirect_to @barangay_fmr_project_completion, notice: 'Barangay fmr project completion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @barangay_fmr_project_completion }
      else
        format.html { render action: 'new' }
        format.json { render json: @barangay_fmr_project_completion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barangay_fmr_project_completions/1
  # PATCH/PUT /barangay_fmr_project_completions/1.json
  def update
    respond_to do |format|
      if @barangay_fmr_project_completion.update(barangay_fmr_project_completion_params)
        format.html { redirect_to @barangay_fmr_project_completion, notice: 'Barangay fmr project completion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @barangay_fmr_project_completion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barangay_fmr_project_completions/1
  # DELETE /barangay_fmr_project_completions/1.json
  def destroy
    @barangay_fmr_project_completion.destroy
    respond_to do |format|
      format.html { redirect_to barangay_fmr_project_completions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barangay_fmr_project_completion
      @barangay_fmr_project_completion = BarangayFmrProjectCompletion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barangay_fmr_project_completion_params
      params.require(:barangay_fmr_project_completion).permit(:barangay_fmr_project_id, :tag, :name, :description, :project_length_provided, :date_confirmed, :user_id, :datetime_edited)
    end
end

app/helpers/barangay_fmr_project_completions_helper.rb
module BarangayFmrProjectCompletionsHelper
end

app/views/barangay_fmr_project_completions/_form.html.erb
<%= form_for(@barangay_fmr_project_completion) do |f| %>
  <% if @barangay_fmr_project_completion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barangay_fmr_project_completion.errors.count, "error") %> prohibited this barangay_fmr_project_completion from being saved:</h2>

      <ul>
      <% @barangay_fmr_project_completion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <label for="barangay_fmr_project_completion_barangay_fmr_project_id">Barangay FMR Project:</label>  <%= f.collection_select :barangay_fmr_project_id, BarangayFmrProject.all, :id, :name_of_fmr_project, :prompt => "Select a Barangay FMR Project " %>
  </div>

  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :project_length_provided %><br>
    <%= f.number_field :project_length_provided %>
  </div>
  <div class="field">
    <%= f.label :date_confirmed %><br>
    <%= f.date_select :date_confirmed %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :datetime_edited %><br>
    <%= f.datetime_select :datetime_edited %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/barangay_fmr_project_completions/edit.html.erb
<h1>Editing barangay_fmr_project_completion</h1>

<%= render 'form' %>

<%= link_to 'Show', @barangay_fmr_project_completion %> |
<%= link_to 'Back', barangay_fmr_project_completions_path %>

app/views/barangay_fmr_project_completions/index.html.erb
<h1>Listing barangay_fmr_project_completions</h1>

<table>
  <thead>
    <tr>
      <th>Barangay fmr project</th>
      <th>Tag</th>
      <th>Name</th>
      <th>Description</th>
      <th>Project Length Provided</th>
      <th>Date confirmed</th>
      <th>User</th>
      <th>Datetime edited</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @barangay_fmr_project_completions.each do |barangay_fmr_project_completion| %>
      <tr>
        <td><%= barangay_fmr_project_completion.barangay_fmr_project.name_of_fmr_project %></td>
        <td><%= barangay_fmr_project_completion.tag %></td>
        <td><%= barangay_fmr_project_completion.name %></td>
        <td><%= barangay_fmr_project_completion.description %></td>
        <td><%= barangay_fmr_project_completion.project_length_provided %></td>
        <td><%= barangay_fmr_project_completion.date_confirmed %></td>
        <td><%= barangay_fmr_project_completion.user_id %></td>
        <td><%= barangay_fmr_project_completion.datetime_edited %></td>
        <td><%= link_to 'Show', barangay_fmr_project_completion %></td>
        <td><%= link_to 'Edit', edit_barangay_fmr_project_completion_path(barangay_fmr_project_completion) %></td>
        <td><%= link_to 'Destroy', barangay_fmr_project_completion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barangay fmr project completion', new_barangay_fmr_project_completion_path %>

app/views/barangay_fmr_project_completions/new.html.erb
<h1>New barangay_fmr_project_completion</h1>

<%= render 'form' %>

<%= link_to 'Back', barangay_fmr_project_completions_path %>

app/views/barangay_fmr_project_completions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Barangay fmr project:</strong>
  <%= @barangay_fmr_project_completion.barangay_fmr_project_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @barangay_fmr_project_completion.tag %>
</p>

<p>
  <strong>Name:</strong>
  <%= @barangay_fmr_project_completion.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @barangay_fmr_project_completion.description %>
</p>

<p>
  <strong>Project Length Provided:</strong>
  <%= @barangay_fmr_project_completion.project_length_provided %>
</p>

<p>
  <strong>Date confirmed:</strong>
  <%= @barangay_fmr_project_completion.date_confirmed %>
</p>

<p>
  <strong>User:</strong>
  <%= @barangay_fmr_project_completion.user_id %>
</p>

<p>
  <strong>Datetime edited:</strong>
  <%= @barangay_fmr_project_completion.datetime_edited %>
</p>

<%= link_to 'Edit', edit_barangay_fmr_project_completion_path(@barangay_fmr_project_completion) %> |
<%= link_to 'Back', barangay_fmr_project_completions_path %>